src/hbcomp/comp/forms.py
from wtforms.fields import StringField, TextAreaField, BooleanField
from wtforms.fields.html5 import IntegerField, DateField
from wtforms.validators import DataRequired
from flask_login import current_user

from ..utils.forms import BaseObjectForm as Form
from ..models import Competition


class CompetitionForm(Form):
    title = StringField(validators=[DataRequired()])
    edition = IntegerField()
    announcement = TextAreaField(validators=[DataRequired()])
    date = DateField(validators=[DataRequired()])
    qualify_date = DateField()
    entries_start_date = DateField(validators=[DataRequired()])
    entries_finish_date = DateField(validators=[DataRequired()])
    url = StringField()
    contact_emails = TextAreaField()
    location = TextAreaField()
    purely_virtual = BooleanField()
    is_active = BooleanField()

    def save(self, obj=None, save=True):
        if obj is None:
            obj = Competition(owner=current_user)
        return super(CompetitionForm, self).save(obj, save)

src/hbcomp/comp/__init__.py
from flask import Blueprint

comp_bp = Blueprint('comp', __name__)

from . import views  # noqa: F401

src/hbcomp/comp/views.py
from flask import render_template, flash, redirect, url_for
from flask_babel import gettext

from ..models import Competition
from ..comp import comp_bp
from ..comp.forms import CompetitionForm


@comp_bp.route('/create', methods=['POST', 'GET'])
def create():
    form = CompetitionForm()
    if form.validate_on_submit():
        comp = form.save()
        flash(gettext('Competition %(name)s has been created', name=comp.title), category='success')
        return redirect(url_for('comp.details', comp_id=comp.id))
    ctx = dict(form=form)
    return render_template('comp/form.html', **ctx)


@comp_bp.route('/<int:comp_id>', methods=['POST', 'GET'])
def details(comp_id):
    comp = Competition.query.get_or_404(comp_id)
    form = CompetitionForm()
    if form.validate_on_submit():
        comp = form.save(obj=comp)
        flash(gettext('Competition %(name)s has been changed', name=comp.title), category='success')
    form = CompetitionForm(obj=comp)
    ctx = dict(comp=comp, form=form)
    return render_template('comp/details.html', **ctx)

src/hbcomp/templates/comp/base.html
{% extends "base.html" %}

src/hbcomp/templates/comp/details.html
{% extends "comp/base.html" %}
{% import "macros/forms.html" as forms %}
{% import "macros/bootstrap.html" as bsu %}

{% block pagetitle %}{{ gettext('Competition %(name)s', name=comp.title) }}{% endblock %}

{% block content %}
<h1>{{ gettext('Competition %(name)s', name=comp.title) }}</h1>
<p class="lead">{% if comp.location %}{{ gettext('Held %(date)s at %(location)s', date=comp.date|dateformat("short"), location=comp.location) }}{% else %}{{ gettext('Held %(date)s', date=comp.date|dateformat("short")) }}{% endif %}.</p>
{% if comp.purely_virtual %}<p>{{ gettext('virtual').capitalize() }}</p>{% endif %}
<h2>{{ gettext('announcement').capitalize() }}</h2>
<p>{{ comp.announcement }}</p>
<h2>{{ gettext('important facts').capitalize() }}</h2>
<dl class="dl-horizontal">
  <dt>{{ gettext('full name') }}:</dt>
  <dd>{{ gettext('%(title)s, edition %(edition)s', title=comp.title, edition=comp.edition) }}</dd>
  <dt>{{ gettext('date') }}:</dt>
  <dd>{{ comp.date|dateformat("short") }}</dd>
  <dt>{{ gettext('entry dates') }}:</dt>
  <dd>{{ gettext("We accept entries from %(start_date)s until %(end_date)s", start_date=comp.entries_start_date|dateformat("short"), end_date=comp.entries_finish_date|dateformat("short")) }}</dd>
  {% if comp.qualify_date %}
  <dt>{{ gettext('qualification date') }}:</dt>
  <dd>{{ comp.qualify_date|dateformat("short") }}</dd>
  {% endif %}
  {% if comp.url or comp.contact_emails %}
  <dt>{{ gettext('contact') }}:</dt>
  <dd>{{ gettext('Web page: %(url)s, emails: %(emails)s', url=comp.url, emails=comp.contact_emails) }}</dd>
  {% endif %}
</dl>
{% if comp.owner == current_user %}
<h2>{{ gettext('change competition data').capitalize() }}</h2>
<form class="form form-horizontal" method="post", action="{{ url_for('comp.details', comp_id=comp.id) }}">
  {{ forms.render(form) }}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">{{ bsu.icon("ok") }} {{ gettext('save') }}</button>
    </div>
  </div>
</form>
{% endif %}
{% endblock %}

src/hbcomp/templates/comp/form.html
{% extends "comp/base.html" %}
{% import "macros/forms.html" as forms %}
{% import "macros/bootstrap.html" as bsu %}

{% block pagetitle %}{% if form.instance %}{{ gettext('Modify competition %(name)s', name=form.instance.title) }}{% else %}{{ gettext('create new competition').capitalize() }}{% endif %}{% endblock %}

{% block content %}
<h1>{% if form.instance %}{{ gettext('Modify competition %(name)s', name=form.instance.title) }}{% else %}{{ gettext('create new competition').capitalize() }}{% endif %}</h1>
<form class="form form-horizontal" method="post", action="{{ url_for('comp.create') }}">
  {{ forms.render(form) }}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">{{ bsu.icon("ok") }} {{ gettext('save') }}</button>
    </div>
  </div>
</form>
{% endblock %}